## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute
#
# HOWTO: use in a workflow
#
# My current workflow is very simple I start by spining up funzzy and 
# then start making my changes, everytime all the tests pass the changed file
# is staged to git. Once I'm done with my changes I simply commit. :)
#
# Run all tasks with `fzz --fail-fast`
# Run quick tasks with `fzz -t @quick --fail-fast`
#
- name: run my build
  run: "make build"
  change: ["Cargo.*"]

- name: run lint and formatter (@quick)
  run: "cargo fmt -- --check {{filepath}}"
  run_on_init: true
  change: 
    - "src/**"
    - "tests/**"
  ignore: 
    - "src/**/*log*"
    - "examples/*.yml"
    - "examples/*.yaml"
    - "examples/workdir/**"

- name: run my test (@quick)
  run: 
    # Filter with `UNIT_TEST=it_replaces_template_with_filepath fzz -t test`
    - "cargo test $UNIT_TEST --verbose"

  change: "src/**"
  run_on_init: true

- name: run integration
  run: 
    # Filter with `INTEGRATION_TEST=watching_configured_rules fzz -t integration`
    - "cargo test --test ${INTEGRATION_TEST:-'*'} -- --nocapture"
  change: 
    - "tests/**/*.rs"
    - "examples/*.yaml"
    - "examples/*.yml"
  ignore: 
    - "examples/workdir/ignored/**"
    - "**/*.log"
  run_on_init: true

- name: after all checks if no error stage to git (@quick)
  run: "git add {{filepath}}"
  change: 
    - "README.md"
    - "src/**"
    - "tests/**"
    - "examples/*.yml"
    - "examples/*.yaml"
  ignore: 
    - "examples/workdir/**"
