## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: run my test
  run: "make tests"
  change: "src/**"
  run_on_init: true

- name: run my lint
  run: "make lint"
  change: "src/**"

- name: run formatter
  run: "cargo fmt"
  change: "src/**"

- name: run integration
  run: "make integration"
  change: "tests/integration/**"
  ignore: "tests/integration/workdir"
  run_on_init: true

- name: run my build
  run: "make build"
  change: ["Cargo.*"]
