## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute
#
- name: run my test (tag:quick)
  run: "make tests"
  change: "src/**"
  run_on_init: true

- name: run my lint (tag:quick)
  run: "make lint"
  change: "src/**"

- name: run formatter (tag:quick)
  run: "cargo fmt"
  change: "src/**"
  ignore: "src/**/*log*"

- name: run integration
  run: "make integration"
  change: "tests/integration/**/*.sh"
  ignore: [
    "tests/integration/workdir/**",
    "tests/integration/release/**",
    "tests/integration/debug/**",
    "tests/integration/*log*",
    "tests/integration/funzzy",
  ]

- name: run my build
  run: "make build"
  change: ["Cargo.*"]
