#!/usr/bin/env bash

NIX_FILE="nix/package-local.nix"

echo "Bumping version to hash"

nix build .# 2> build.log

SHA256=$(grep "got:" build.log | grep -o "sha256-.*=" | cut -d'-' -f2)
echo "cargo hash SHA256: $SHA256"
sed -i "s#cargoHash = \".*\";#cargoHash = \"sha256-$SHA256\";#" "$NIX_FILE"

echo "Building nix derivation"
nix build .#

rm -f build.log
