name: Release artifacts for arm7

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

jobs:

  build_arm:
    env:
      TARGET: armv7-unknown-linux-gnueabihf
      RELEASE_TAG: v1.1.1
      # CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: /usr/bin/arm-linux-gnueabihf-gcc

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu18.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Install gcc tools
        run: 
          sudo apt install gcc-arm-linux-gnueabihf

      - name: Create artifacts folder
        run: mkdir artifacts

      - name: Create artifacts for darwin
        run: sh ci/script.sh

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: funzzy-${{ env.RELEASE_TAG }}-${{ env.TARGET }}.tar.gz
          asset_name: funzzy-${{ env.RELEASE_TAG }}-${{ env.TARGET }}.tar.gz
          tag: v1.1.1
          overwrite: true
