name: CI integration tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: rust:1.67

    steps:
      - uses: actions/checkout@v3

      - name: Install depedencies
        run: apt-get install -y vi

      - name: Run integration tests
        run: make integration
