name: CI integration tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  integration-batch-1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run integration tests second batch
        run: bash tests/integration/batches.sh 5

  integration-batch-2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run integration tests second batch
        run: bash tests/integration/batches.sh 10

  integration-batch-3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run integration tests second batch
        run: bash tests/integration/batches.sh 15
