name: CI Checks

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: make prebuild

      - name: Linter 
        run: make lint

      - name: Run unit tests
        run: make tests

      - name: Run integration
        run: make integration
