name: Release artifacts

on:
  release:
    types: [created]

jobs:
  build_release_osx:
    env:
      TARGET: x86_64-apple-darwin

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create artifacts folder
        run: mkdir artifacts

      - name: Release info
        run: echo "RELEASE_TAG=${GITHUB_REF_NAME//(\/|\.)/_}" >> $GITHUB_ENV

      - name: Create artifacts for darwin
        run: sh ci/script.sh

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/funzzy-${{ env.RELEASE_TAG }}-${{ env.TARGET }}.tar.gz
          asset_name: funzzy-${{ env.RELEASE_TAG }}-${{ env.TARGET }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

  build_release_linux:
    env:
      TARGET: x86_64-unknown-linux-gnu
      RELEASE_TAG: ${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create artifacts folder
        run: mkdir artifacts

      - name: Release info
        run: echo "RELEASE_TAG=${GITHUB_REF_NAME//(\/|\.)/_}" >> $GITHUB_ENV

      - name: Create artifacts for linux
        run: sh ci/script.sh

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/funzzy-${{ env.RELEASE_TAG }}-${{ env.TARGET }}.tar.gz
          asset_name: funzzy-${{ env.RELEASE_TAG }}-${{ env.TARGET }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

  publish_crates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Publish crate
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
